/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderProviderIdRouteImport } from './routes/provider.$providerId'
import { Route as ChatRequestIdRouteImport } from './routes/chat.$requestId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderProviderIdRoute = ProviderProviderIdRouteImport.update({
  id: '/provider/$providerId',
  path: '/provider/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRequestIdRoute = ChatRequestIdRouteImport.update({
  id: '/chat/$requestId',
  path: '/chat/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/chat/$requestId': typeof ChatRequestIdRoute
  '/provider/$providerId': typeof ProviderProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/chat/$requestId': typeof ChatRequestIdRoute
  '/provider/$providerId': typeof ProviderProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/chat/$requestId': typeof ChatRequestIdRoute
  '/provider/$providerId': typeof ProviderProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/chat/$requestId'
    | '/provider/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/search' | '/chat/$requestId' | '/provider/$providerId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/search'
    | '/chat/$requestId'
    | '/provider/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  ChatRequestIdRoute: typeof ChatRequestIdRoute
  ProviderProviderIdRoute: typeof ProviderProviderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$providerId': {
      id: '/provider/$providerId'
      path: '/provider/$providerId'
      fullPath: '/provider/$providerId'
      preLoaderRoute: typeof ProviderProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$requestId': {
      id: '/chat/$requestId'
      path: '/chat/$requestId'
      fullPath: '/chat/$requestId'
      preLoaderRoute: typeof ChatRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  ChatRequestIdRoute: ChatRequestIdRoute,
  ProviderProviderIdRoute: ProviderProviderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
